version: "3"

services:

  vault:
    image: vault:latest
    container_name: onion-test-vault
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: 12345
    ports:
      - "8200:8200"

  test:
    build: .
    volumes:
      - .:/opt/workdir
    depends_on:
      - vault
    links:
      - vault
    environment:
      VAULT_URL: http://vault:8200
      VAULT_TOKEN: 12345
    command: npm run test